version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    ports:
      - ${APACHE_PORT}:80
    container_name: ${PROJECT_NAME}-php
    depends_on:
      - mysql
    volumes:
      - ./wordpress:/var/www/html:delegated
    environment:
      XDEBUG_CONFIG: "remote_host=${LOCALHOST} remote_enable=1 remote_mode=req remote_port=9005 remote_connect_back=0 idekey=PHPSTORM extended_info=1"
      PHP_IDE_CONFIG: "serverName=dev.localhost"
      PHP_XDEBUG_ENABLED: "1"
    links:
      - 'mysql'
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --sql_mode=''
    container_name: ${PROJECT_NAME}-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
